# Generated by Django 5.0.4 on 2024-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='original_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='processed_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
