# Generated by Django 5.0.4 on 2024-11-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_uploadmodel_original_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='processed_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
