# Generated by Django 5.0.4 on 2024-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_uploadmodel_processed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='original_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='processed_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
