# Generated by Django 5.0.4 on 2024-11-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_uploadmodel_original_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='original_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
