# Generated by Django 5.0.4 on 2024-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_uploadmodel_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='processed_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
